web:
    resource: '@AppBundle/Controller/Web'
    type: annotation
    prefix: '/'
api:
    resource: '@AppBundle/Controller/Api'
    type: annotation
    prefix: '/api/'

#user_auth:
#    resource: '@UserBundle/Controller/'
#    type: annotation
#    prefix: '/auth'

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile